config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'users/:id/taskboard', :to => 'my_taskboard#index'
post 'users/:id/taskboard/save', :to => 'my_taskboard#save'
get 'my/taskboard', :to => 'my_taskboard#my_index'
get 'projects/:project_id/taskboard', :to => 'taskboard#index'
post 'projects/:project_id/taskboard/save', :to => 'taskboard#save'
post 'projects/:project_id/taskboard/archive-issues', :to => 'taskboard#archive_issues'
post 'issues/:issue_id/taskboard-unarchive', :to => 'taskboard#unarchive_issue'
post 'projects/:project_id/taskboard/columns/create', :to => 'taskboard#create_column', :as => :project_taskboard_columns_create
delete 'projects/:project_id/taskboard/columns/:column_id/delete', :to => 'taskboard#delete_column', :as => :project_taskboard_columns_delete
put 'projects/:project_id/taskboard/columns/update', :to => 'taskboard#update_columns', :as => :project_taskboard_columns_update

app/controllers/taskboard_controller.rb
class TaskboardController < ApplicationController
  unloadable

  before_filter :find_project
  before_filter :authorize
  helper_method :column_manager_locals
  helper TagsHelper if defined?(TagsHelper)

  def index
    @columns = TaskBoardColumn.where(:project_id => @project.id).order('weight').all()
    @status_names = Hash.new
    IssueStatus.select([:id, :name]).each do |status|
      @status_names[status.id] = status.name
    end
    @include_subprojects = \
          Setting.plugin_redmine_task_board['include_subprojects'].to_i == 1 &&
          @project.children.active.any?
    category_finder = :issue_categories
    if @include_subprojects && @project.respond_to?(:inherited_categories)
      category_finder = :inherited_categories
    end
    @categories = @project.send(category_finder)
  end

  def save
    failed_issues = []
    if params[:move] then
      params[:move].each do |issue_id, new_status_id|
        issue = Issue.find(issue_id)
        if issue.new_statuses_allowed_to(User.current).include?(IssueStatus.find(new_status_id))
          issue.init_journal(User.current)
          issue.update_attribute(:status_id, new_status_id)
        else
          failed_issues << issue
        end
      end
    end
    if failed_issues.empty?
      params[:sort].each do |status_id, issues|
        weight = 0;
        issues.each do |issue_id|
          tbi = TaskBoardIssue.find_by_issue_id(issue_id).update_attribute(:project_weight, weight)
          weight += 1
        end
      end
    end
    respond_to do |format|
      format.js do
        if failed_issues.empty?
          head :ok
        else
          response = failed_issues.map do |issue|
            cards = TaskBoardIssue.find_all_by_issue_id(Project.all.first.issues.where(:status_id => issue.status_id)).sort{|a,b| a.project_weight <=> b.project_weight}
            index = cards.index{|i| i.issue_id == issue.id}
            prev_card_id = (index.nil? || index < 1) ? false : cards[index-1].issue_id
            {:issue_id => issue.id, :status_id => issue.status_id, :previous_sibling_id => prev_card_id}
          end
          render :json => response, :status => 403
        end
      end
    end
  end

  def archive_issues
    params[:ids].each do |issue_id|
      TaskBoardIssue.find_by_issue_id(issue_id).update_attribute(:is_archived, true)
    end
    respond_to do |format|
      format.js{ head :ok }
    end
  end

  def unarchive_issue
    TaskBoardIssue.find_by_issue_id(params[:issue_id]).update_attribute(:is_archived, false)
    respond_to do |format|
      format.js{ head :ok }
    end
  end

  def create_column
    @column = TaskBoardColumn.new :project => @project, :title => params[:title]
    @column.save
    render 'settings/update'
  end

  def delete_column
    @column = TaskBoardColumn.find(params[:column_id])
    @column.delete
    render 'settings/update'
  end
  
  def update_columns
    params[:column].each do |column_id, new_state|
      column = TaskBoardColumn.find(column_id.to_i)
      print column.title + ' ' + new_state[:weight] + ". "
      column.weight = new_state[:weight].to_i
      column.max_issues = new_state[:max_issues].to_i
      column.save!
      column.status_buckets.clear()
    end
    params[:status].each do |column_id, statuses|
      statuses.each do |status_id, weight|
        status_id = status_id.to_i
        column_id = column_id.to_i
        StatusBucket.create!(:task_board_column_id => column_id, :issue_status_id => status_id, :weight => weight)
      end
    end
    render 'settings/update'
  end

  private

  def find_project
    # @project variable must be set before calling the authorize filter
    if (params[:project_id]) then
      @project = Project.find(params[:project_id])
    elsif(params[:issue_id]) then
      @project = Issue.find(params[:issue_id]).project
    end
  end

end

app/helpers/taskboard_helper.rb
module TaskboardHelper
end

app/views/taskboard/_issue_description.html.erb
<% if tbi = TaskBoardIssue.find_by_issue_id(@issue.id) and tbi.is_archived? then %>
  <div id="taskboard-issue">
    <hr>
    <p><strong><%= translate :label_task_board %></strong></p>
    <p>
      <%= translate :task_board_issue_archived %>
      <input type="button" id="taskboard-unarchive" value="<%= translate :task_board_issue_unarchive %>" />
    </p>
  </div>

  <script type="text/javascript">
    $('#taskboard-unarchive').on('click', function() {
      $('#ajax-indicator').show();
      new $.ajax('/issues/<%= @issue.id %>/taskboard-unarchive', {
        type: 'post',
        complete: function() {
          $('#ajax-indicator').hide();
        },
        success: function() {
          $('#taskboard-issue').remove();
        }
      });
    });
  </script>
<% end %>

app/views/taskboard/index.html.erb
<%= javascript_include_tag('jquery.ui.touch-punch.min', :plugin => 'redmine_task_board') %>
<%= javascript_include_tag('task_board', :plugin => 'redmine_task_board') %>

<div id="taskboard-filters">
  <p>
    <%= label_tag "assignee", l(:task_board_assignee) %>
    <%
      author_values = [[l(:task_board_anyone), '0']]
      author_values << ["<< #{l(:label_me)} >>", User.current.id] if User.current.logged?
      author_values += @project.members.collect { |m| [ m.name, m.user.id ] }
    %>
    <%= select_tag("assignee", options_for_select(author_values)) %>
    <%= label_tag "priority", l(:task_board_priority) %>
    <%= select_tag("priority", options_for_select([[l(:task_board_any), '0']] + IssuePriority.all.collect { |m| [ m.name, m.id ] } )) %>
    <%= label_tag "category", l(:task_board_category) %>
    <%= select_tag("category", options_for_select([[l(:task_board_any), '0']] + @categories.collect { |m| [ m.name, m.id ] } )) %>
    <% if @include_subprojects %>
      <%= label_tag "project", l(:task_board_project) %>
      <%= select_tag("project", options_for_select([[l(:task_board_any), '0']] + @project.children.active.collect { |m| [ m.name, m.id ] } )) %>
    <% end %>
  </p>
</div>

<div id="taskboard-buttons">
  <input type="button" id="edit-issues" value="<%= translate :task_board_issue_bulk_edit %>" />
  <input type="button" id="archive-issues" value="<%= translate :task_board_issue_bulk_archive %>" />
</div>

<div class="taskboard-wrapper" id="sortable-root">
  <% @columns.each do|column| %>
    <div class="taskboard-pane">
      <h2><%= column.title %></h2>
      <% column.issues.each do |status_id, issues| %>
        <% unless column.issues.size == 1 %>
          <h3 class="status"><%= @status_names[status_id] %></h3>
        <% end %>
        <ul data-status-id="<%= status_id %>" data-max-issues="<%= column.max_issues %>" id="column_<%= status_id %>"<% if issues.empty? %> class="empty"<% end %>>
          <% issues.each do|issue| %>
            <li class="card priority-<%= issue.priority.id.to_s %> <%= issue.tracker.name.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '') %>" id="issue_<%= issue.id %>" data-issue-id="<%= issue.id %>" data-priority="<%= issue.priority.id.to_s %>" data-assignee="<%= issue.assigned_to ? issue.assigned_to.id.to_s : 0 %>" data-category="<%= issue.category ? issue.category.id.to_s : 0 %>" data-weight="<%= issue.weight %>" data-status-id="<%= issue.status_id %>" data-project="<%= issue.project_id %>">
              <div class="issue">
                <div class="issue-heading">
                  <p class="issue-number meta">
                    <input type="checkbox" name="ids[]" value="<%= issue.id.to_s %>" />
                    <%= link_to "#{issue.tracker} ##{issue.id.to_s}", :controller => :issues, :action => :show, :id => issue.id %>
                  </p>
                  <p class="issue-priority">
                    <%= issue.priority.name %>
                  </p>
                </div>
								<h3>
									<% if respond_to? :render_tag_link %>
										<span class='tag-list'>
											<%= safe_join(issue.tag_counts.collect{ |t| render_tag_link(t, :show_count => false, :open_only => false) }) %>
										</span>
									<% end %>
									<%= link_to((issue.category ? issue.category.name + ': ' : '') + issue.subject, :controller => :issues, :action => :show, :id => issue.id) %>
								</h3>
                <% if defined? issue.assigned_to.name %>
                  <p class="meta">
                    <%= link_to issue.assigned_to.name, :controller => :users, :action => :show, :id => issue.assigned_to.id %>
                  </p>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  var project_save_url = '<%= Redmine::Utils::relative_url_root %>/projects/<%= @project.id %>/taskboard/save';
  var project_archive_url = '<%= Redmine::Utils::relative_url_root %>/projects/<%= @project.id %>/taskboard/archive-issues';
  var sections = [];
  $('#sortable-root .taskboard-pane ul').each(function() {
    sections.push($(this).attr('id'));
  });
  for (var i in sections) {
    new TaskBoardPane(sections[i], {connectWith: '#sortable-root .taskboard-pane ul', constraint: false, scroll: true, dropOnEmpty: true, items: '> .card'});
  }
  TaskBoardUtils.checkboxListener();
  var filters = new TaskBoardFilters();
  // Sortable.create('sortable-root', {tree: true, dropOnEmpty: true, constraint: false, overlap: 'vertical'});
</script>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'taskboard', :plugin => 'redmine_task_board' %>
	<%= stylesheet_link_tag 'redmine_tags', :plugin => 'redmine_tags' if respond_to? :render_tag_link%>
<% end %>