config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'users/:id/taskboard', :to => 'my_taskboard#index'
post 'users/:id/taskboard/save', :to => 'my_taskboard#save'
get 'my/taskboard', :to => 'my_taskboard#my_index'
get 'projects/:project_id/taskboard', :to => 'taskboard#index'
post 'projects/:project_id/taskboard/save', :to => 'taskboard#save'
post 'projects/:project_id/taskboard/archive-issues', :to => 'taskboard#archive_issues'
post 'issues/:issue_id/taskboard-unarchive', :to => 'taskboard#unarchive_issue'
post 'projects/:project_id/taskboard/columns/create', :to => 'taskboard#create_column', :as => :project_taskboard_columns_create
delete 'projects/:project_id/taskboard/columns/:column_id/delete', :to => 'taskboard#delete_column', :as => :project_taskboard_columns_delete
put 'projects/:project_id/taskboard/columns/update', :to => 'taskboard#update_columns', :as => :project_taskboard_columns_update

app/views/settings/_column_manager.html.erb
<%= form_tag project_taskboard_columns_create_path(:project_id => @project.id), :remote => true, :id => 'create-column' do %>
  <p>
    <%= label_tag(:title, translate(:task_board_column_title)) %>
    <%= text_field_tag(:title) %>
    <%= submit_tag(translate :task_board_create_column) %>
  </p>
<% end %>

<%= form_tag project_taskboard_columns_update_path(:project_id => @project.id), :method => 'put', :remote => true do %>
  <div class="status-bucket column">
    <h5><%= translate(:task_board_available_status) %></h5>
    <p><em><%= translate(:task_board_status_config_message) %></em></p>
    <ul class="buckets-wrapper status-holder">
      <% statuses.each do |status| %>
        <% if TaskBoardColumn.empty_status(@project.id, status.id) %>
          <li class="status-pill" data-status-id="<%= status.id.to_s %>"><%= status.name %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="movable-columns" id="taskboard-columns">
    <% columns.each do |column| %>
      <div class="column dyn-column" data-column-id="<%= column.id.to_s %>">
        <div class="input-wrapper"></div>
        <h5><%= column.title %></h5>
        <div class="column-meta">
          <%= link_to(
            l(:button_delete),
            project_taskboard_columns_delete_path(:project_id => @project.id, :column_id => column.id),
            :method => :delete,
            :confirm => l(:text_are_you_sure),
            :remote => true,
            :class => 'icon icon-del'
            )
          %>
          <p class="cell">
            <%= label_tag("column[#{column.id}][max_issues]", translate(:task_board_task_limit)) %>
            <%= text_field_tag("column[#{column.id}][max_issues]", column.max_issues, :class => 'column-max-issues') %>
            <%= hidden_field_tag("column[#{column.id}][weight]", column.weight, :class => 'column-weight') %>
          </p>
        </div>
        <ul class="buckets-wrapper status-holder clearfix">
          <% column.issue_statuses.each do |status| %>
            <li class="status-pill" data-status-id="<%= status.id.to_s %>"><%= status.name %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="form-save">
    <%= submit_tag(translate :task_board_save_changes) %>
  </div>
<% end %>

<script type="text/javascript">
  var taskboard_columns = new TaskBoardSettings('taskboard-columns', {tag: 'div', items: '> div.column', handle: 'h5', weightSelector: '.column-options .column-weight', axis: 'x'});
  var taskboard_statuses = new TaskBoardStatuses('status-holder', {connectWith: '.status-holder'});
</script>

app/views/settings/_project.html.erb
<%= javascript_include_tag('jquery.ui.touch-punch.min', :plugin => 'redmine_task_board') %>
<%= javascript_include_tag('task_board', :plugin => 'redmine_task_board') %>

<style>
.status-holder { list-style-type: none; margin: 0; padding: 0; }
.status-pill { list-style-type: none; cursor: move; float: left; background: #efefef; border: solid 1px #aaa; margin: 0 5px 5px 0; padding: 5px; border-radius: 3px; }

#column_manager { overflow: auto }
#column_manager div.movable-columns h4 { text-align: center; height: 15px; padding: 5px 0; margin: 0 0 5px 0; font-size: 15px; }
#column_manager .column { float: left; width: 165px; margin-right: 10px; padding: 5px; }
#column_manager .column.dyn-column { background: #fafafa; border: solid 1px #ccc; }
#column_manager .column h5 { font-size: 16px; margin: 0 0 5px 0; padding: 0; cursor: move; }
#column_manager .column .buckets-wrapper { border: dashed 1px #ccc; padding: 5px; }
#column_manager .column .buckets-wrapper .status-pill { float: none; }
#column_manager div.form-save { clear: left; padding-top: 15px; }

#column_manager ul.status-holder { width: 150px; }
p.cell input { width: 30px; }
.clearfix:before, .clearfix:after { content: ""; display: table; }
.clearfix:after { clear: both; }
.clearfix { zoom: 1; }
</style>

<%= translate :task_board_help %>

<div id="column_manager">
  <%= render :partial => 'settings/column_manager', :locals => {
        :columns => TaskBoardColumn.where(:project => @project.id).order("weight ASC"),
        :statuses => IssueStatus.all
      }
  %>
</div>

app/views/settings/_redmine_task_board_settings.erb
<p>
  <label><%= l(:label_task_board_include_subprojects) %></label>
  <%= check_box_tag 'settings[include_subprojects]', 1, settings['include_subprojects'] %>
</p>

app/views/settings/update.js.erb
$('#column_manager').html("<%= escape_javascript( render(
:partial => 'settings/column_manager',
:locals => {
  :columns => TaskBoardColumn.where(:project => @project.id).order('weight ASC'),
  :statuses => IssueStatus.all
})) -%>");